export default {
  SELECTION: {
    CURRENT_SELECTION: 0,
    SELECT_FIELD_VALUE: 1,
    DISREGARD_SELECTION: 2,
  },
  DIMENSION: {
    ONE_DIMENSION: 0,
    ALL_DIMENSIOANS: 1,
    DISREGARD_ALL_DIMENSIONS: 2,
  },
};
