name: 'Create release'

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_BUILD }}

      - name: git config
        run: |
          git config user.name "github-action"
          git config user.email "github-action@noreply.github.com"
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      # - run: npm run generateDocs
      - run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }} # Add npm publish token to .npmrc
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
